### ISSUE TITLE
Create 3 Personas

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#12]
### Description: 
In order to better understand users needs and wants, let's create 3 user personas. 
For each persona the following must be included:
1. Photo
2. Demographic information. Age, income, education
3. Professional title. Student, salesperson, physician, etc.
4. Other details relevant to our app
5. Has a story. Which exemplifies the persona's skills, feelings, attitudes, concerns, relationships
6. Has goals as it pertains to using our app. That is, what does the user want (goal)? that our app will help in achieving. For example, Bob wants to get fit, so he uses an app to keep track of his workouts.
7. Different from the other personas. Do they belong to different groups of users of your app?

### Tasks:
- [x] Create Gary Gamer - Evan
- [x] Create Terry Tryhard - Jackson
- [x] Create Casual Casey - Ethan

### Notes:
Add at least three personas, one wiki page for each, to your wiki. These should cover 3 distinct user-types for your app. Each Persona must have a name, photo, and personal history.
Have someone review your wiki page after you create it
