### ISSUE TITLE
Create User Stories

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#16]
### Description:
With our personas, stories will be associated with each one. These pertain their needs and wants when it comes to our website. 
Let's each create 1 story for each of our personas. We will have 15 stories, then choose the best 9 to add to the "User Stories" wiki
### Tasks:
- [x] Create 3 stories - James
- [ ] Create 3 stories - Ethan
- [x] Create 3 stories - Aaron
- [ ] Create 3 stories - Jackson
- [x] Create 3 stories - Evan

### Notes:
Things we need to consider.
1. Are there at least 9 user stories?
2. Do they reflect important part of the app's functionality?
3. Is some important functionality missing from the user stories?

Add a "User Stories" wiki page with at least 9 user stories covering the most common use cases for your app. They should all be of the form: As [the name of one of your personas] I want a [feature] so that I can [satisfy a need].

We will do this^^ once we choose the 9 stories
