### ISSUE TITLE
Create 'User Stories' Wiki Page

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#22]
### Description:
After creating many different user stories in #16 we have narrowed down our top 9. It is now time to create the wiki page and transfer our stories to it. 

### Tasks:
- [x] Create 'User Stories' wiki
- [x] Add our 9 stories (see [here](https://github.com/SCCapstone/PalmettoProgrammers/issues/16#issuecomment-1714580504))
- [x] Have someone review

### Notes:
Some of those stories may need small revisions. For example, Terrys story 'As Terry, I would like to find a time me and my group members are able to play together' needs to be reworded. Also ensure all stories include what need is being satisfied.
