### ISSUE TITLE
Sketch Rough Designs

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#23]
### Description:
Before using a diagram tool to design our website, let's have each of us sketch out how we think the site should look. That way when we meet next we can discuss and share our sketches, then jump into a real design.

### Tasks:
- [x] Create a rough design - James
- [x] Create a rough design - Ethan
- [x] Create a rough design - Evan
- [x] Create a rough design - Jackson
- [x] Create a rough design - Aaron

### Notes:
Some important things to include in your design. 
- Login
- Signup/Onboarding process
- User profiles
- Group pages
- Gamer Discovery
- Chat
- Posts/Comments/Forum
