### ISSUE TITLE
Evan SignalR Research

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#24]
### Description:
Since this site will be mostly used by gamers it is important that they are able to quickly message one another without having to refresh the page to see new messages. We will be using a live chat feature to achieve this, so that users can quickly message other users and their groups.

Let's create a demo app so that when we get to coding our actual idea, it will be easy to incorporate live chat. After this demo is complete users should be able to:
1. Signup
2. Login
3. Message Users

Pages this demo will likely need:
1. Signup
2. Login
3. Chats (Similar to Instagram/Twitter just display a list of all chats the user is a part of)
4. Chat page
     4a. Again similar to Instagram/Twitter, open a chat to see all messages in it and be able to send messages
     4b. Don't worry about being able to leave the chat or rename it or add/remove users from a group chat
5. Create Group Chat
     5a. Allow a user to name the chat
     5b. Display a list of all users that the user is able to add to the chat
     5c. Display a list of all users the user has chosen to add to the chat
     5d. Include the 'Create Group Chat' button, which will bring us to the chat page between the users
     5e. Again don't worry about any chat settings (like adding or removing users)

### Tasks:
- [x] Design database objects
- [x] Setup initial ASP.NET project
- [x] Figure out SignalR stuff
- [x] Setup initial React project
- [x] Create Auth Controller
- - [x] Create Login endpoint
- - [x] Create Register endpoint
- - [x] Create Search endpoint  (Get's a user by username - username must exactly match)
- - [x] Create Get endpoint (Get's the current signed in user)
- [x] Create Chat Controller
- - [x] Create GetChats endpoint
- - [x] Create CreateChat endpoint
- - [x] Create GetChat endpoint
- [x] Create Message Controller
- - [x] Create SaveMessage endpoint
- - [x] Create GetMessages endpoint
- [x] Create SignalR Chat Hub
- [x] Create sign up page
- [x] Create sign in page
- [x] Create home page
- [x] Create create chat page
- [x] Create chat page
- [x] Deploy api on azure with github actions
- [x] Get database on azure
- [x] Deploy frontend with github actions

Part of Evan's personal research milestone, code moved to personal repo found [here](https://github.com/SCCapstone/research-evan-scales)

### Notes:
After some initial research looks like we should use something called SignalR 2 to help with this.
Let's also just use 1 service named CommonService in the backend
Might also add ability to confirm linked steam account to this demo
