### ISSUE TITLE
Create Pages on Figma

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#27]
### Description:
After meeting up and going over all of our rough sketches, it is now time to start creating our Figma designs.
We will each start some pages, then meetup again and make adjustments as we see. 

### Tasks:
- [x] Start header (Logged in vs logged out) - Evan
- [x] Start 'sign in' page - Evan
- [x] Start 'sign up' page - Evan
- [x] Start user profile page - Jackson
- [x] Start 'social' page - Ethan
- [x] Start 'discovery' page - James
- [x] Start 'home' page - Aaron
- [x] Start 'chat' page - James
- [x] Start 'group' page - Jackson
- [x] Start 'create' page - Aaron
- [x] Start 'post' page - Ethan

Add pages as you see fit

### Notes:
Header needs to be completed first so we can all be using the same header. When designing your pages use the signed in header
Design milestone is due October 1. 
Let's have all the pages started by 9/27, then we will make the adjustments whenever.
