### ISSUE TITLE
Decide on Game Roles for Supported Games

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#31]
### Description:
As a part of the user onboarding process a user can select the games they are interested in. They can also select their roles in those selected games to assist with filtering. Let's figure out the games roles for our supported games. Then update the supported games wiki page with these game roles

### Tasks:
Figure out game roles for the following games:
- [x] Rainbow Six Siege
- [x] Fortnite
- [x] Overwatch 2
- [x] CS:GO
- [x] Valiant
- [ ] Call of Duty
- [ ] Insurgency: Sandstorm
- [ ] Insurgency
- [x] Baldur's Gate 3
- [x] Destiny 2
- [x] Diablo 4
- [ ] GTFO
- [ ] Update Supported Games Wiki

### Notes:
See '[Supported Games](https://github.com/SCCapstone/PalmettoProgrammers/wiki/Supported-Games)' wiki page
I don't think all of these games will have game roles, which is okay. For example, Fortnite. But will still include in tasks until its confirmed

### Related Issues:
- #6
