### ISSUE TITLE
Research Competition

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#4]
### Description:
As part of the development process for our idea, it is essential that we have a clear understanding of our competition. This research will also provide valuable insights into what similar platforms are offering, their strengths, and their weaknesses. With our new understanding of similar platforms, we can better position ourselves to stand out and try to offer the best features.

### Tasks:
- [ ] List if they have features we have discussed to implement
- [ ] Compile a list of 2-4 similar websites
- [ ] List if they have features you think we should implement
- [ ] Analyze the websites and summarize your findings

### Notes:
Feel free to edit this directly with a new section, or leave comments with your findings
