### ISSUE TITLE
Research React

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#5]
### Description:
To enhance the visual appeal and functionality of our web app, we're initiating a research phase focused on React, a popular frontend framework. This research will primarily involve understanding the prerequisites and setup needed for incorporating React into our project.

### Tasks:
- [x] Dive into React's core concepts and features
- [x] Gain familiarity with React's component-based architecture
- [x] Identify the tools and dependencies required for React development (What do we need to install?)
- [x] Summarize findings, highlighting why React is the right framework for us

### Notes:
Here is a [React tutorial project](https://react.dev/learn/tutorial-tic-tac-toe), with [example code](https://stackblitz.com/edit/react-tic-tac-toe-official-tutorial?file=index.js).
Don't actually have to do the full tutorial, but look into it and start a sample project. Let us know what we need to install, and share any nice React videos you find here. 

Won't include this in the tasks since this part is still a bit away. But start looking into component libraries for React. When I did some work with Angular before I used something called [Angular Material](https://material.angular.io/components/categories). Maybe there is something similar for React.

Feel free to edit this directly with a new section, or leave comments with your findings.
