### ISSUE TITLE
List Joined Groups

### ISSUE THREAD

**Issue by epadams** [SCCapstone/PalmettoProgrammers#56]
### Description: 
The user should be able to see a list of groups they are a part of.

### Tasks:
- [ ] Add Groups page under Social
- [ ] Implement Joining Groups
- [ ] Display view under Social

### Notes:
