### ISSUE TITLE
Upload Profile Picture

### ISSUE THREAD

**Issue by Jackson-Williams-15** [SCCapstone/PalmettoProgrammers#60]
### Description
The user should be able to upload a profile image in our PoC
### Tasks
- [x] Have the image display correctly
- [ ] Implement uploading backend
- [ ] Save to database
- [ ] Implement relevant views for uploading and displaying
