### ISSUE TITLE
Research PostgreSQL

### ISSUE THREAD

**Issue by evan-scales** [SCCapstone/PalmettoProgrammers#7]
### Description:
In our pursuit of optimizing our web app's data management, we're initiating a research phase focused on PostgreSQL, a robust open-source relational database system. This research will primarily involve understanding the prerequisites and setup needed for incorporating PostgreSQL into our project.

### Tasks:
- [x] Dive into PostgreSQL's core concepts and features
- [x] Familiarize yourself with PostgreSQL's relational data model and benefits
- [x] Identify the tools and dependencies required for PostgreSQL development (What do we need to install?)
- [x] Summarize findings, highlighting why PostgreSQL is right for us

### Notes:
Let us know what we need to install, and share any nice PostgreSQL videos you find here. 

Feel free to edit this directly with a new section, or leave comments with your findings.
